require("destructive.plugins")
require("destructive.color")

map('n', '<leader>w', ':w<CR>',{noremap = false})
map('n', '<leader>q', ':q!<CR>',{noremap = false})
map('n', '<leader>s', ':so %<CR>',{noremap = false})
map('n', '<leader>ev', ':vsplit $MYVIMRC<CR>',{noremap = false})
map('n', '<leader>sv', ':w<CR>:so %<CR>:q<CR>',{noremap = false})
map('n', '<Leader>p', '"+p')
--map('n', '<C-n>', ':NERDTree .<CR>')
map('n', '<C-n>', ':NvimTreeFindFileToggle.<CR>')
map('n', '<leader>gm', "<cmd>lua require('frontmatter').Frontmatter('add',{'image_url', 'series'})<cr>")
map('n', '<Leader>pv', ':vsplit ~/.config/nvim/lua/destructive/plugins.lua<CR>')
map('n', '<Leader>kv', ':vsplit ~/.config/nvim/lua/destructive/keymap.lua<CR>')
map('n', '<Leader>nv', ':vsplit ~/.config/nvim/<CR>')
map('t', '<Esc>', '<C-\\><C-n>')
map("v", "J", ":m '>+1<CR>gv=gv")
map("v", "K", ":m '<-2<CR>gv=gv")

local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, {})
vim.keymap.set('n', '<leader>fg', builtin.live_grep, {})
vim.keymap.set('n', '<leader>fb', builtin.buffers, {})
vim.keymap.set('n', '<leader>fh', builtin.help_tags, {})
